"""
Generate a tiny MJPEG + PCM .avi clip and emit it as a C byte array in
kernel/sample_video.h, for the Phase 40 AVI parser / media player.

The clip is a bouncing colour ball on a gradient, 80x60, 16 frames at 8 fps,
with a per-frame stepped tone (8 kHz mono 16-bit) so audio + video advance
together. Hand-written AVI muxer (RIFF/hdrl/strl/movi). Run: python gen_video.py
"""
from PIL import Image, ImageDraw
import io, struct, math

OUT  = "kernel/sample_video.h"
W, H = 80, 60
NF   = 16
FPS  = 8
US_PER_FRAME = 1000000 // FPS
ARATE = 8000
ASPF  = ARATE // FPS              # audio samples per frame

def make_frames():
    jpgs, pcms = [], []
    for i in range(NF):
        im = Image.new("RGB", (W, H))
        px = im.load()
        for y in range(H):
            for x in range(W):
                px[x, y] = (x * 3 & 255, y * 4 & 255, 96)
        d = ImageDraw.Draw(im)
        t = i / (NF - 1)
        cx = int(8 + t * (W - 16))
        cy = int(H / 2 + 18 * math.sin(t * math.pi * 2))
        col = (255 - i * 12, 60 + i * 10, 80 + i * 8)
        d.ellipse([cx - 8, cy - 8, cx + 8, cy + 8], fill=col)
        b = io.BytesIO(); im.save(b, "JPEG", quality=80, subsampling=0)
        jpgs.append(b.getvalue())

        # stepped tone for this frame
        freq = 330 + i * 30
        buf = bytearray()
        for n in range(ASPF):
            s = int(9000 * math.sin(2 * math.pi * freq * n / ARATE))
            buf += struct.pack("<h", s)
        pcms.append(bytes(buf))
    return jpgs, pcms

def chunk(fcc, data):
    out = fcc + struct.pack("<I", len(data)) + data
    if len(data) & 1: out += b"\x00"
    return out

def lst(listtype, payload):
    data = listtype + payload
    return b"LIST" + struct.pack("<I", len(data)) + data

def build_avi(jpgs, pcms):
    total_samples = NF * ASPF
    # avih (MainAVIHeader, 56 bytes)
    avih = struct.pack("<IIIIIIIIIIIIII",
        US_PER_FRAME, 0, 0, 0, NF, 0, 2, 0, W, H, 0, 0, 0, 0)
    # video strh (56) + strf (BITMAPINFOHEADER, 40)
    strh_v = (b"vids" + b"MJPG" + struct.pack("<IHHIIIIIIII",
        0, 0, 0, 0, 1, FPS, 0, NF, 0, 0xFFFFFFFF, 0)
        + struct.pack("<hhhh", 0, 0, W, H))
    strf_v = struct.pack("<IiiHHIIiiII", 40, W, H, 1, 24,
        0x47504A4D, W * H * 3, 0, 0, 0, 0)            # 'MJPG'
    strl_v = lst(b"strl", chunk(b"strh", strh_v) + chunk(b"strf", strf_v))
    # audio strh (56) + strf (WAVEFORMATEX, 16)
    block = 2                                          # mono 16-bit
    strh_a = (b"auds" + struct.pack("<I", 0) + struct.pack("<IHHIIIIIIII",
        0, 0, 0, 0, 1, ARATE, 0, total_samples, 0, 0xFFFFFFFF, block)
        + struct.pack("<hhhh", 0, 0, 0, 0))
    strf_a = struct.pack("<HHIIHH", 1, 1, ARATE, ARATE * block, block, 16)
    strl_a = lst(b"strl", chunk(b"strh", strh_a) + chunk(b"strf", strf_a))

    hdrl = lst(b"hdrl", chunk(b"avih", avih) + strl_v + strl_a)
    movi_payload = b""
    for i in range(NF):
        movi_payload += chunk(b"00dc", jpgs[i])
        movi_payload += chunk(b"01wb", pcms[i])
    movi = lst(b"movi", movi_payload)

    body = b"AVI " + hdrl + movi
    return b"RIFF" + struct.pack("<I", len(body)) + body

def main():
    jpgs, pcms = make_frames()
    avi = build_avi(jpgs, pcms)
    with open(OUT, "w") as f:
        f.write("/* Auto-generated by gen_video.py — Phase 40 demo MJPEG+PCM AVI. */\n\n")
        f.write("#ifndef SAMPLE_VIDEO_H\n#define SAMPLE_VIDEO_H\n\n")
        f.write("static const unsigned char demo_avi[] = {\n")
        for i in range(0, len(avi), 16):
            f.write("    " + ",".join("0x%02X" % c for c in avi[i:i+16]) + ",\n")
        f.write("};\n")
        f.write("#define DEMO_AVI_LEN %du\n\n" % len(avi))
        f.write("#endif /* SAMPLE_VIDEO_H */\n")
    print("wrote", OUT)
    print("  %dx%d  %d frames @ %d fps  %d us/frame  audio %d Hz" %
          (W, H, NF, FPS, US_PER_FRAME, ARATE))
    print("  total AVI size: %d bytes  (avg jpeg %d B/frame)" %
          (len(avi), sum(len(j) for j in jpgs) // NF))

if __name__ == "__main__":
    main()
