"""
Generate small sample images (BMP / PNG / JPEG / GIF) and emit them as C byte
arrays in kernel/sample_images.h, for the Phase 39 image decoders + viewer.

Each image is kept under the RAM-FS 4 KB per-file cap so it can be installed as
a real file at boot (icon.bmp / logo.png / photo.jpg / anim.gif) and opened with
`view <file>`. Run:  python gen_images.py
"""
from PIL import Image, ImageDraw
import io

OUT = "kernel/sample_images.h"

def make_icon_bmp():
    """32x32, four solid quadrants — trivially verifiable pixels."""
    im = Image.new("RGB", (32, 32))
    px = im.load()
    for y in range(32):
        for x in range(32):
            if   x < 16 and y < 16: px[x, y] = (220, 40, 40)    # TL red
            elif x >= 16 and y < 16: px[x, y] = (40, 200, 60)   # TR green
            elif x < 16 and y >= 16: px[x, y] = (50, 90, 230)   # BL blue
            else:                    px[x, y] = (240, 240, 240)  # BR white
    b = io.BytesIO(); im.save(b, format="BMP"); return im, b.getvalue()

def make_logo_png():
    """48x48 RGB: gradient background + accent disc + ring."""
    im = Image.new("RGB", (48, 48))
    px = im.load()
    for y in range(48):
        for x in range(48):
            px[x, y] = (x * 5 & 255, y * 5 & 255, 128)
    d = ImageDraw.Draw(im)
    d.ellipse([10, 10, 38, 38], fill=(250, 200, 40))
    d.ellipse([18, 18, 30, 30], fill=(40, 40, 60))
    b = io.BytesIO(); im.save(b, format="PNG", optimize=True); return im, b.getvalue()

def make_photo_jpg():
    """48x48 'photo': smooth gradients; 4:4:4 (subsampling=0) baseline JPEG."""
    im = Image.new("RGB", (48, 48))
    px = im.load()
    for y in range(48):
        for x in range(48):
            px[x, y] = ((x * 255) // 47, (y * 255) // 47, ((x + y) * 255) // 94)
    b = io.BytesIO()
    im.save(b, format="JPEG", quality=90, subsampling=0, optimize=False)
    return im, b.getvalue()

def make_anim_gif():
    """32x32, 3 frames: a coloured block sweeping left->right (animation)."""
    frames = []
    cols = [(230, 60, 60), (60, 200, 80), (80, 120, 240)]
    for i in range(3):
        im = Image.new("RGB", (32, 32), (24, 24, 32))
        d = ImageDraw.Draw(im)
        x = 2 + i * 9
        d.rectangle([x, 8, x + 8, 24], fill=cols[i])
        frames.append(im.convert("P", palette=Image.ADAPTIVE, colors=16))
    b = io.BytesIO()
    frames[0].save(b, format="GIF", save_all=True, append_images=frames[1:],
                   duration=300, loop=0)
    return frames[0], b.getvalue()

def emit(f, name, data):
    f.write("static const unsigned char img_%s[] = {\n" % name)
    for i in range(0, len(data), 16):
        f.write("    " + ",".join("0x%02X" % c for c in data[i:i+16]) + ",\n")
    f.write("};\n")
    f.write("#define IMG_%s_LEN %du\n\n" % (name.upper(), len(data)))

def main():
    items = [
        ("icon_bmp",  "icon.bmp",  make_icon_bmp()),
        ("logo_png",  "logo.png",  make_logo_png()),
        ("photo_jpg", "photo.jpg", make_photo_jpg()),
        ("anim_gif",  "anim.gif",  make_anim_gif()),
    ]
    with open(OUT, "w") as f:
        f.write("/* Auto-generated by gen_images.py — Phase 39 sample images. */\n")
        f.write("/* Small BMP/PNG/JPEG/GIF blobs installed into the RAM-FS at boot. */\n\n")
        f.write("#ifndef SAMPLE_IMAGES_H\n#define SAMPLE_IMAGES_H\n\n")
        for cname, _fname, (_im, data) in items:
            emit(f, cname, data)
        f.write("typedef struct { const char* name; const unsigned char* data; unsigned int len; } sample_image_t;\n")
        f.write("static const sample_image_t sample_images[] = {\n")
        for cname, fname, _ in items:
            f.write('    { "%s", img_%s, IMG_%s_LEN },\n' % (fname, cname, cname.upper()))
        f.write("};\n")
        f.write("#define SAMPLE_IMAGE_COUNT %d\n\n" % len(items))
        f.write("#endif /* SAMPLE_IMAGES_H */\n")

    print("wrote", OUT)
    for cname, fname, (im, data) in items:
        w, h = im.size
        # corner + center sample pixels (for decoder verification)
        rgb = im.convert("RGB")
        def p(x, y): return rgb.getpixel((x, y))
        print("  %-10s %-9s %dx%d  %4d bytes  TL=%s C=%s BR=%s" %
              (cname, fname, w, h, len(data), p(0, 0), p(w//2, h//2), p(w-1, h-1)))

if __name__ == "__main__":
    main()
